baseURL = "https://jamie.so/"
languageCode = "en-us"
title = "DevOps = People over Process over Tools"
publishDir = "docs"
theme = "beautifulhugo"


[params]
  DateForm = "Mon Jan 2, 2006"
  DateFormat = "Mon Jan 2, 2006"

